name = "vkmuzpremium-stars-payments"
main = "worker.js"
compatibility_date = "2026-09-28"
workers_dev = true

[[d1_databases]]
binding = "DB"
database_name = "vkmuzpremium_stars"
database_id = "40242619-57f6-48d3-ade6-50402707dde1"
